# Incoming
mp.messaging.incoming.operativt-uppgiftslager-status-notification.connector=smallrye-kafka
mp.messaging.incoming.operativt-uppgiftslager-status-notification.auto.offset.reset=earliest
mp.messaging.incoming.operativt-uppgiftslager-status-notification.value.deserializer=se.fk.rimfrost.framework.oul.presentation.kafka.OulStatusNotificationDeserializer
